### ISSUE TITLE
SHREKUS

### ISSUE THREAD

**Issue by ZELOS467** [Apix0n/Armus#19]
# 🤺 Ajouter un personnage

## L'image:

* ![Shrekus](https://user-images.githubusercontent.com/69749011/196253300-fccdaf50-f231-474e-9798-de4d29a07552.jpg)

---

## Le nom du personnage:

* SHREKUS

---

## Votre nom dans les remerciements:

* NISSOU

**Comment by Apix0n** [comment]
❗ Ce personnage existe déjà sur le site!
