### ISSUE TITLE
Werbrus

### ISSUE THREAD

**Issue by ZELOS467** [Apix0n/Armus#20]
# 🤺 Ajouter un personnage

## L'image:

* ![WERBRUS](https://user-images.githubusercontent.com/69749011/196254459-5ef7fa50-13b3-4b7e-895e-46f3e507eedb.jpg)

---

## Le nom du personnage:

* WERBRUS

---

## Votre nom dans les remerciements:

* NISSOU

**Comment by Apix0n** [comment]
Je vais le rajouter!
